### ISSUE TITLE
Cannot connect to server "epp.server.tld"

### ISSUE THREAD

**Issue by cenourinha** [getnamingo/whmcs-epp-registrar#1]
Hi there! First of all, thank you for creating this module.

I'm trying to use it to connect to "registry.nic.mz" (port 700) but i'm getting this error:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/58000/211679809-6d2151ef-1c2a-40d7-a3d2-bc17c274f675.png">

I already have added the exceptions for the connection in the Firewall and it's connecting correctly:

```
# nc -zv registry.nic.mz 700
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 196.3.103.50:700.
Ncat: 0 bytes sent, 0 bytes received in 0.21 seconds.
```

In the Registrar module configuration, i've set the fields "EPP Server", "Server Port", "Client ID" and "Password" with the correct information. The other fields are empty.

**Comment by cenourinha** [comment]
Ok, i fixed by changing:

`$this->socket = stream_socket_client("tlsv1.3://{$host}:{$port}", $errno, $errmsg, $timeout, STREAM_CLIENT_CONNECT, $context);`

to

`$this->socket = stream_socket_client("tlsv1.2://{$host}:{$port}", $errno, $errmsg, $timeout, STREAM_CLIENT_CONNECT, $context);`

**Comment by getpinga** [comment]
Thanks for noticing that, I'll add in the next version the ability to select the TLS version in settings. I was testing it only with EPP servers that have mandatory TLS 1.3

**Comment by getpinga** [comment]
I've applied the fix.
