### ISSUE TITLE
where to upload cert file

### ISSUE THREAD

**Issue by Thamizhanaruldass** [getnamingo/whmcs-epp-registrar#10]
I have placed all certificates in the same Epp directory,
but it is not fetching the certificate to execute, when I check openssl it's connected with the server, but through the application, it says "Cannot connect to server 'epp.registry.in':"

**Comment by anantsparrow** [comment]
> I have placed all certificates in the same Epp directory, but it is not fetching the certificate to execute, when I check openssl it's connected with the server, but through the application, it says "Cannot connect to server 'epp.registry.in':"

Hi there, are you still facing the issue?

**Comment by Thamizhanaruldass** [comment]
Hi,
The issue resolved already, now everything working perfectly,
Thanks for asking
