### ISSUE TITLE
Request | Accept DS Records

### ISSUE THREAD

**Issue by whitetiger264** [getnamingo/whmcs-epp-registrar#15]
Please provide the option to add DS records to a domain name for DNSSec security. Should be able to add the following when adding a DS to a domain name:

- Algorithm
- Digest Type
- Digest
- Key Tag

This is specifically for the Cocca EPP system, if possible, please.

**Comment by whitetiger264** [comment]
@getpinga I want to add to this, it should also allow you to delete the DS records.

**Comment by getpinga** [comment]
@whitetiger264 This has been added in latest version, please test.

**Comment by whitetiger264** [comment]
@getpinga Hey, sorry I have been busy. I finally managed to get time to test the new code. Where exactly do I add and remove DS records for domain names via the WHMCS UI? I do not see it on the domain admin page in WHMCS.

EDIT:

Ignore, I see you added it to the client area UI and not the admin UI. Tested and seems to work well with the CoCCA system, thank you.

**Comment by getpinga** [comment]
You are welcome.
