### ISSUE TITLE
No Domain Sync via Cron

### ISSUE THREAD

**Issue by whitetiger264** [getnamingo/whmcs-epp-registrar#16]
Currently, its not possible to sync your domain names with the EPP system via cronjobs, as far as I can see. Do you have any plans to include this? To ensure domain names remain in sync with the registry, for domain status, expiry dates etc.

**Comment by getpinga** [comment]
Hello, I will start workin on it soon.

**Comment by mikkihugo** [comment]
Would be awesome for us. Were moving into this and whmcs so sync would be helpful <3

**Comment by getpinga** [comment]
Ok, double checked. No need for separate cron scripts as the supported WHMCS versions rely on 2 Sync functions we already implement.

**Comment by getpinga** [comment]
Closing this as the required sync is already in the module. If you experience issues with it, please open a separate ticket.
