### ISSUE TITLE
The WHMCS version 8.8.0 can use this epp?

### ISSUE THREAD

**Issue by hebaotan** [getnamingo/whmcs-epp-registrar#17]
================= Error 2: =================
stream_socket_client(): unable to connect to tlsv1.3://epp.ote.mynicregistry.my:700 (Connection refused) on line 1893 in file /home/domain/public_html/whmcs-x/modules/registrars/epp/epp.php

**Comment by getpinga** [comment]
Try to select TLS 1.2 from settings, and also make sure your IP is whitelisted with the registry.
