### ISSUE TITLE
whmcs-epp-rfc issue with contacts

### ISSUE THREAD

**Issue by wvro-org** [getnamingo/whmcs-epp-registrar#18]
error 
WHMCS "Order Accept Encountered Problems
Object does not exist : domain:registrant does not exist"

whmcs-epp-rfc issue with 'contacts' in epp.php in function epp_RegisterDomain 
it try's to use non-existent contact for example 
contact R3-BILLING1 but in namingo registry it doesn't exist ...
to my mind the function should have ability to create contact if the contact doesn't exist

**Comment by wvro-org** [comment]
this fix isn't very suitable for production environmet... 

log in namingo registry db and sql following

`
CREATE TEMPORARY TABLE IF NOT EXISTS temp_number_series (
    n INT
);

INSERT INTO temp_number_series (n)
SELECT n
FROM (
    SELECT 1 AS n -- Start from 1 -- change 1 to number you want to start from 
    UNION ALL
    SELECT n + 1
    FROM temp_number_series
    WHERE n < 200 -- Chage number up to  your desired quantity  be carefull with large quantity
) AS r;
`





INSERT INTO `contact` (
    `identifier`, 
    `voice`, 
    `voice_x`, 
    `fax`, 
    `fax_x`, 
    `email`, 
    `nin`, 
    `nin_type`, 
    `clid`, 
    `crid`, 
    `crdate`, 
    `upid`, 
    `lastupdate`, 
    `trdate`, 
    `trstatus`, 
    `reid`, 
    `redate`, 
    `acid`, 
    `acdate`, 
    `disclose_voice`, 
    `disclose_fax`, 
    `disclose_email`, 
    `validation`, 
    `validation_stamp`, 
    `validation_log`
)
SELECT 
    CONCAT('R3-REGISTRANT', n),  -- repeat this whole sql for each type R3-BILLING , R3-REGISTRANT, R3-ADMIN, R3-TECH
    '+example.voice', 
    NULL, 
    NULL, 
    NULL, 
    'email@example.com', 
    NULL, 
    NULL, 
    '3', 
    '3', 
    '2024-04-30 21:28:46.714',  -- change to your desired date
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    2, 
    2, 
    2, 
    NULL, 
    NULL, 
    NULL,
    NULL 
FROM 
    temp_number_series
WHERE 
    n BETWEEN 1 AND 200; -- Chage numbesr up to  your desired quantity  be carefull with large quantity (for example there's allready R3-REGISTRANT from 1 to to 25 so change to 25-200)

**Comment by getpinga** [comment]
Yes, it is supposed to create contacts if they do not exist. I'll test it next week.

**Comment by anantsparrow** [comment]
> Yes, it is supposed to create contacts if they do not exist. I'll test it next week.

facing the same issue

**Comment by anantsparrow** [comment]
@wvro-org , did you manage to fix this out? so you can share me, using in production

**Comment by anantsparrow** [comment]
@getpinga mate, can you fix this out? we are eagerly waiting to launch our sld domains

**Comment by getpinga** [comment]
The new version finally fixes this, thank you for your patience.
