### ISSUE TITLE
Get EPP sends mail instead of showing code

### ISSUE THREAD

**Issue by cenourinha** [getnamingo/whmcs-epp-registrar#2]
Hi there again!

I see that you are getting the EPP Code and sending it to the Registrant Contact Email. It would be great if you could change this behavior or have an option for us to decide if we want to send the epp code via mail or show it to the client.

Note: I've changed the code myself to have this result, as you simply have it commented :)

**Comment by getpinga** [comment]
Thanks, will add such option soon.

**Comment by getpinga** [comment]
I've applied the fix.
