### ISSUE TITLE
'Oops! Something went wrong' after adding epp folder to the /var/www/html/modules/registrars folder

### ISSUE THREAD

**Issue by aaronjrodrigues** [getnamingo/whmcs-epp-registrar#23]
I followed the instructions and added the 'epp' folder containing the repository, I then followed step 3 to activate the add on but Im getting an error page saying oops something went wrong. Please assist me as to what the issue could be, thank you

**Comment by aaronjrodrigues** [comment]
Also I noticed its asking me to put my key.pem and cert.pem however I dont have one, where do I get it?

**Comment by getpinga** [comment]
Could you share the screenshot of the error message? Also to what registry you connect, this will help me tell you from where to get the SSLs.

**Comment by aaronjrodrigues** [comment]
I'm trying to connect to the BOCRA registry (handles .bw domains for botswana). Here's the error message:

<img width="1512" alt="Screenshot 2024-10-29 at 10 37 47" src="https://github.com/user-attachments/assets/67f2bd84-2c34-4172-8071-8b8e34c465e6">

Thank you for your assistance

**Comment by getpinga** [comment]
Sorry for delay, please try 

```bash
chown -R www-data:www-data /var/www/html/whmcs/modules/registrars/epp
chmod -R 755 /var/www/html/whmcs/modules/registrars/epp
```

and let me know if worked.

**Comment by getpinga** [comment]
As for the SSL, you can generate with the following:

```bash
openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 365
```

Place them in the same directory where the script is.

**Comment by aaronjrodrigues** [comment]
it worked! thank you!
