### ISSUE TITLE
Getting error on validation

### ISSUE THREAD

**Issue by anantsparrow** [getnamingo/whmcs-epp-registrar#3]
XML schema validation failed: Element '{urn:ietf:params:xml:ns:epp-1.0}pw': [facet 'maxLength'] The value has a length of '18'; this exceeds the allowed maximum length of '16'.

the error

**Comment by getpinga** [comment]
> XML schema validation failed: Element '{urn:ietf:params:xml:ns:epp-1.0}pw': [facet 'maxLength'] The value has a length of '18'; this exceeds the allowed maximum length of '16'.
> 
> the error

Thank you for noticing that, what registry (TLD) are you using? I'll check their specifications.

**Comment by anantsparrow** [comment]
We are using centralnic registry for .in.net tld and .pw

**Comment by getpinga** [comment]
I've implemented a small fix, can you re-download the module and test again?

**Comment by anantsparrow** [comment]
still same error

**Comment by getpinga** [comment]
Then please comment out this line https://github.com/getpinga/whmcs-epp-rfc/blob/main/epp.php#L2057 , try again and send me to tk@getpinga.com the epp.log file from the module directory.

**Comment by anantsparrow** [comment]
done

**Comment by getpinga** [comment]
Thank you, seen the problem. It fails on the login because your centralnic registrar password is 18 characters, you need to change it to 16 and try again.

**Comment by getpinga** [comment]
It is a limit in the Centralnic server.

**Comment by anantsparrow** [comment]
hi, sorry for the issue, there was some password misconfiguration in mine, solved it and working fine now. 

transfer domain is working with your module?

**Comment by getpinga** [comment]
Yes, both transfer request and transfer sync are working.

**Comment by anantsparrow** [comment]
great, does your this module support https://github.com/GoDaddyRegistry/registrar-toolkit ?

**Comment by getpinga** [comment]
Not yes, I'll have a look at it. Thanks.

**Comment by anantsparrow** [comment]
hmm sure, cause this supports lots of tlds like .in etc

**Comment by getpinga** [comment]
This is to confirm that the module has been tested with GoDaddy and supports all their TLDs.

**Comment by anantsparrow** [comment]
how will i use this module for different tlds from different registry. like centralnic or godaddy. i will have different ssl files for both registry then?

**Comment by getpinga** [comment]
1. Put them in different folders, named centralnic and godaddy
2. Rename the PHP file inside to centralnic.php or godaddy.php
3. In whmcs.json change name: epp to name: centralnic or name: godaddy
4. In the php file, search and replace epp_ to centralnic_ or godaddy_ . Be careful not to replace it twice on epp_epp_client
5. After that activate and setup the modules.

Let me know if you experience any issues. There is no multiple support in WHMCS unfortunately, to have all this in one module.
