### ISSUE TITLE
authInfo code is invalid: password must be at least 16 characters

### ISSUE THREAD

**Issue by anantsparrow** [getnamingo/whmcs-epp-registrar#4]
getting this while activating new orders.

**Comment by anantsparrow** [comment]
authInfo code is invalid: password must be at least 16 characters

**Comment by getpinga** [comment]
Please re-download the module and try again.

**Comment by anantsparrow** [comment]
already using your latest version. Nameservers fetch etc are working perfectly. but while accepting the orders it is showing error. looks like the auth key generation is not working, or may be something else.

**Comment by getpinga** [comment]
Can you send me again the log file to tk@getpinga.com ?

**Comment by anantsparrow** [comment]
done

**Comment by getpinga** [comment]
Please download again, I just updated the epp.php file, and try one more time.

**Comment by anantsparrow** [comment]
working now

**Comment by getpinga** [comment]
Ok, thanks for the help. Closing the issue now.
