### ISSUE TITLE
after upload downloaded file, module is not showing in "Domain registrar Module config page"?

### ISSUE THREAD

**Issue by Thamizhanaruldass** [getnamingo/whmcs-epp-registrar#5]
I have downloaded and uploaded the main file zip, after unzipping the file, went to the domain registrar config
the module is not listed there, why?

**Comment by getpinga** [comment]
Hi,
What version of WHMCS are you using?

Also, can you confirm that you extracted the file correctly? Is there a file called [WHMCS_path]/modules/registrars/epp/epp.php ?

**Comment by Thamizhanaruldass** [comment]
Yeah, after renamed the folder as "epp" now it's showing, thank you.
