### ISSUE TITLE
Failed to read header from the connection

### ISSUE THREAD

**Issue by Thamizhanaruldass** [getnamingo/whmcs-epp-registrar#6]
Hi,
I have configure certificate file and private key properly,
But I'm getting error of "Failed to read header from the connection"
![Screenshot_2023-03-08-08-10-54-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/61128847/223606611-2b10aff9-eaee-408a-81b4-9bf9730a2c48.jpg)
How to solve this??
Thanks in advance

**Comment by getpinga** [comment]
Hi,
Things you need to check:
- Are you running WHMCS on virtual server on a shared hosting.
- Is the server IP whitelisted with the domain registry you are using. Try running 
```
openssl s_client -connect epp.example.com:700 -CAfile cacert.pem -cert cert.pem -key key.pem
```
- Also, to which registry you are trying to connect?

**Comment by Thamizhanaruldass** [comment]
Hi,
Virtual server with cyberpanel
Yes Server ip is white listed
Trying to connect .in registry

**Comment by idealapps-code** [comment]
> Hi, Virtual server with cyberpanel Yes Server ip is white listed Trying to connect .in registry

You should put certificate and key file in the same folder as module and enter their names in the configuration page.
