### ISSUE TITLE
connection error  

### ISSUE THREAD

**Issue by kevinpareek** [getnamingo/whmcs-epp-registrar#7]
Hello

during
`openssl s_client -connect epp.ote.registry.in:700`
CONNECTED(00000003)

but when i use your WHMCS module i am facing errors

================= Error 1: =================
stream_socket_client(): Unable to set local cert chain file `/home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/onekick_epp-csr.pem'; Check that your cafile/capath settings include details of your certificate and its issuer on line 1893 in file /home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/epp.php
================= Error 2: =================
stream_socket_client(): Failed to enable crypto on line 1893 in file /home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/epp.php
================= Error 2: =================
stream_socket_client(): unable to connect to tlsv1.2://epp.ote.registry.in:700 (Unknown error) on line 1893 in file /home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/epp.php

**Comment by kevinpareek** [comment]
<img width="1096" alt="Screenshot 2023-03-14 at 10 39 24 PM" src="https://user-images.githubusercontent.com/58112179/225084225-381874d2-43f8-43e1-857d-86b8e84ff59f.png">

check i use correct configuration

**Comment by kevinpareek** [comment]
one more when i use

`$ openssl s_client -connect epp.ote.registry.in:700 -CAfile onekick_epp_ote.pem -cert onekick_epp-csr.pem -key onekick_epp-key.pem`

unable to load certificate
23394883630992:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE

**Comment by getpinga** [comment]
Hi,
Please leave CA File empty,
and in Certificate put the onekick_epp_ote.pem file and try again.
And uncheck the Verify peer.

Let me know about the result.

**Comment by kevinpareek** [comment]
> 

same error 

================= Error 2: =================
stream_socket_client(): Unable to set local cert chain file `/home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/onekick_epp-csr.pem'; Check that your cafile/capath settings include details of your certificate and its issuer on line 1893 in file /home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/epp.php
================= Error 2: =================
stream_socket_client(): Failed to enable crypto on line 1893 in file /home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/epp.php
================= Error 2: =================
stream_socket_client(): unable to connect to tlsv1.2://epp.ote.registry.in:700 (Unknown error) on line 1893 in file /home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/epp.php

**Comment by getpinga** [comment]
Can you make sure if this file exists actually in the mentioned path?
/home/qwbgigignjfgjfhd/public_html/modules/registrars/epp/onekick_epp-csr.pem

Also, try downloading the latest version of the module - 0.6.2
