### ISSUE TITLE
command syntax error

### ISSUE THREAD

**Issue by anantsparrow** [getnamingo/whmcs-epp-registrar#8]
error while updating nameservers on tld from FRED registry

**Comment by getpinga** [comment]
Hello,
Which is the TLD you are trying to connect to?

Also, FRED is supported only in https://github.com/getpinga/fossbilling-epp-fred or the tembo client so please make sure you use one of them. FRED module for WHMCS does not exist yet, and the RFC module will not work, as FRED has too many extensions.
