### ISSUE TITLE
Registry support and SSL?

### ISSUE THREAD

**Issue by TinnieDevNorway** [getnamingo/whmcs-epp-registrar#9]
Hello, are NORID (registry for .no tld) supported with this one?

also i am wondering since NORID, doesn't require SSL for the EPP connection, so i wonder if i do have to use a certificate in the communication?

Also there are these options which i don't quite get:
- Client ID
- Registrar Prefix

As a registrar at NORID we get assigned a "reg1xxx" which are our registrar identifier, as well we get a username, so which of those are which in the module?

Thank you! :-)

**Comment by getpinga** [comment]
Hello,

For now the module requires SSL.
If you don't have a certificate, you can generate a test one

openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 365

Registrar Prefix you choose a random string, no needed for .no  For client ID, this is your epp login name, I guess it's the username.

If you have any other questions, will be happy to help.
